/**
 * gaSend — den RENE dom for platformens afsendelse til Google Analytics 4
 * (Measurement Protocol). Udkast 21/9-2026 aften; samme form som metaSend.ts.
 * Deno-fri, så vitest dækker den (src/lib/__tests__/gaSend.test.ts). Afsendelsen
 * (fetch + api_secret) bor i gaSendAfsendelse.ts; kørslen i ga-send-cron.
 *
 * BESLUTTET (chatten 21/9, Jonas' fulde mandat; docs/tracking.md §1c, §1f, §1g):
 *   - Ejendom G-6LHR66CDJ4 (theboardroom.dk). To hændelser: application_started
 *     (created_at) og application_submitted (indsendt_at) — samme to navne som
 *     hjemmesidens GTM-tags, så tallene kan lægges sammen.
 *   - KUN rækker med ga_client_id. Cookien _ga findes kun, når ansøgeren har sagt ja
 *     til cookies på theboardroom.dk (Consent Mode default 'denied' siden 21/9) — så
 *     samtykket ER betingelsen. Intet gæt, intet genereret id.
 *   - client_id = ansoegninger.ga_client_id; session_id = ga_session_id, når den er sat.
 *   - Kun inden for Googles 72-timersvindue. Intet forsøgsloft: VINDUET er loftet.
 *   - Ingen persondata (Googles politik) — FORBUDTE_NOEGLER + findForbudteNoegler på
 *     den faktiske payload, både i prøven og i drift.
 *   - Låsen app_config.ga_send_aktiv (standard false) er bevisets: cronen tørkører,
 *     indtil den ene hændelse er valideret mod /debug/mp/collect og set i Realtime.
 *
 * GOOGLES DOKUMENTATION, citeret ordret (hentet 21/9-2026 aften):
 *   Påkrævet · endpoint · EU — https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events
 *     «The `client_id` should match the ID generated by the Google Analytics tag on your website.»
 *     «If you want your data to be collected in the EU, change the HOST in the example to
 *      `region1.google-analytics.com`.»  → derfor GA_HOST nedenfor.
 *     «Creating a new `session_id` creates a new session without the need to send `session_start`.»
 *       → vi opfinder ALDRIG et session_id: er ga_session_id null, udelades feltet, så vi
 *         ikke bryder ansøgerens løbende session op i en ny.
 *     «Events and user properties can be backdated up to 72 hours. If the `timestamp_micros`
 *      value is earlier than 72 hours ago … If the `validation_behavior` is not set or is set
 *      to `RELAXED`, the Measurement Protocol accepts the event or user property but overrides
 *      its timestamp to 72 hours ago.» → vi sender ikke ældre end 72 t; et overskrevet
 *       tidsstempel ville være en løgn i deres rapport.
 *     «Events sent using the Measurement Protocol that are intended to be joined … with events
 *      collected by … gtag.js should be received by Google Analytics within 48 hours of the
 *      original client-side event timestamp. Events received later than this may not be
 *      processed as expected, particularly for purposes like conversion attribution.»
 *       → MELLEM 48 OG 72 TIMER: hændelsen ACCEPTERES og tælles, men kan ikke længere regnes
 *         med til besøgets kilde. Vi sender den alligevel (tallet er rigtigt; tilskrivningen
 *         er usikker) — og cronen kører hvert tiende minut, så det næsten aldrig sker.
 *   Felterne — https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference
 *     «A Unix timestamp, microseconds, not milliseconds.» (timestamp_micros)
 *     «To ensure accurate session and user engagement metrics in your reports, including
 *      Realtime, include the `session_id` and `engagement_time_msec` parameters with your
 *      events. While events sent without these parameters may still appear in some reports,
 *      they won't contribute correctly to metrics like Average engagement time or Engaged
 *      sessions, and these events may not be fully reflected in Realtime user counts.»
 *     «The duration of user engagement, in milliseconds, for the event. Use a value that
 *      reflects the amount of user engagement time since the preceding event.»
 *       → EN SÆRSKILT ANBEFALING FOR SERVER-HÆNDELSER ER IKKE FUNDET i dokumentationen.
 *         Googles eget eksempel på siden «sending events» bruger `"engagement_time_msec": 100`,
 *         og det er værdien her (ENGAGEMENT_TIME_MSEC). Vi MÅLER ikke engagementtid på
 *         serveren; 100 ms er Googles eksempelværdi, ikke en måling — det står her, så ingen
 *         læser tallet som noget, vi har regnet.
 *     «If you don't specify `consent`, Google Analytics uses the consent settings from
 *      corresponding online interactions for the client or app instance.»
 *       → derfor sendes INTET consent-objekt: ansøgerens eget svar på banneret på
 *         theboardroom.dk gælder, og vi kan ikke sige det bedre end hende selv.
 *     «Up to 25 events can be sent per request.» · event-navne «40 characters or fewer» ·
 *     «Up to 25 parameters» · parameterværdier «must be 100 characters or fewer for a
 *      standard Google Analytics property.»
 *     Reserverede navne: parametre må ikke begynde med `_`, `firebase_`, `ga_`, `google_`
 *      eller `gtag.` → derfor hedder parametrene kilde/utm_* og ALDRIG ga_client_id.
 *   Validering — https://developers.google.com/analytics/devguides/collection/protocol/ga4/validating-events
 *     «The Google Analytics Measurement Protocol does not return HTTP error codes, even if an
 *      event is malformed or missing required parameters.»
 *     «The validation server's URL includes "/debug" unlike the standard Measurement Protocol URL.»
 *     «Events sent to the validation server don't show up in reports.»
 *     «Caution: The validation server does not validate the `api_secret` or `firebase_app_id`.»
 *       → BEVISET ER TODELT: /debug/mp/collect siger, om payloaden er gyldig (validationMessages),
 *         men IKKE om nøglen er rigtig. Kun en rigtig hændelse i Realtime viser det.
 *   Politik — https://developers.google.com/analytics/devguides/collection/protocol/ga4/policy
 *     «You must not upload any data that allows Google to personally identify an individual
 *      (such as certain names, Social Security Numbers, email addresses, or any similar data)»
 *     «You must obtain consent from your end users, or otherwise provide them with the
 *      opportunity to opt-out from the implementations and features you use.»
 *
 * INGEN DEDUPLIKERING HOS GOOGLE. Meta dedup'er på event_id; Measurement Protocol har
 * ingen tilsvarende — sender vi den samme hændelse to gange, tælles den to gange. Derfor er
 * VORES spor (ga_haendelser, event_id som primærnøgle) den eneste idempotens, og sporet
 * skrives efter hvert eneste kald.
 */
import { kbhDato } from "./hverdage.ts";

/** Ejendommen (theboardroom.dk). Offentlig i begge GTM-containere — ikke en hemmelighed. */
export const GA_MEASUREMENT_ID = "G-6LHR66CDJ4";
/** EU-værten (Googles egen sætning ovenfor). */
export const GA_HOST = "region1.google-analytics.com";
export const GA_STI = "/mp/collect";
export const GA_DEBUG_STI = "/debug/mp/collect";
/** Secret-navnet. IKKE GA4_API_SECRET — det navn hører til sitets eget repo (ga4-track). */
export const GA_SEND_SECRET_NAVN = "GA4_SEND_SECRET";
/** app_config-nøglen (låsen). Standard false. */
export const GA_SEND_LAAS_NOEGLE = "ga_send_aktiv";
export const GA_TIMEOUT_MS = 8000;
/** Backdating-grænsen. */
export const GA_VINDUE_TIMER = 72;
/** Grænsen for at kunne joines med gtag.js-hændelser. Mellem de to sendes der stadig. */
export const GA_JOIN_TIMER = 48;
/** Googles eksempelværdi — ikke en måling. */
export const ENGAGEMENT_TIME_MSEC = 100;
/** Googles grænse for en parameterværdi på en standard-ejendom. */
export const VAERDI_MAKS = 100;

export const ARTER = ["started", "submitted"] as const;
export type Art = (typeof ARTER)[number];

/** Samme to navne som hjemmesidens GTM-tags (docs/tracking.md §1b). Begge ≤ 40 tegn og ikke reserverede. */
export const GA_EVENT_NAVN: Readonly<Record<Art, string>> = {
  started: "application_started",
  submitted: "application_submitted",
};

/** Sporets nøgle. Sendes IKKE til Google (MP har ingen dedup) — den er vores egen. */
export function eventId(ansoegningId: string, art: Art): string {
  return `${ansoegningId}:${art}`;
}

const somTid = (v: string | null | undefined): Date | null => {
  if (typeof v !== "string" || v.trim() === "") return null;
  const t = Date.parse(v);
  return Number.isFinite(t) ? new Date(t) : null;
};

/** Inden for Googles backdating-vindue: 0 ≤ nu − tid ≤ 72 timer. */
export function erIVindue(tid: Date, nu: Date): boolean {
  const alder = nu.getTime() - tid.getTime();
  return alder >= 0 && alder <= GA_VINDUE_TIMER * 3_600_000;
}

/** Kan hændelsen stadig joines med besøget? Under 48 t. Sendes uanset — men svaret siger det. */
export function kanJoines(tid: Date, nu: Date): boolean {
  return nu.getTime() - tid.getTime() <= GA_JOIN_TIMER * 3_600_000;
}

/** Rækken, cronen læser — og INTET andet (ingen navn, email, telefon, cvr, svar, user agent, fbclid). */
export interface AnsoegningTilGa {
  id: string;
  created_at: string;
  indsendt_at: string | null;
  ga_client_id: string | null;
  ga_session_id: string | null;
  kilde: string | null;
  utm_source: string | null;
  utm_medium: string | null;
  utm_campaign: string | null;
  utm_content: string | null;
  utm_term: string | null;
}

export const SPRUNGET_GRUNDE = ["ingen_ga_client_id", "ikke_indsendt", "ingen_tidspunkt", "for_gammel"] as const;
export type SprungetGrund = (typeof SPRUNGET_GRUNDE)[number];

export type Dom = { ok: true; tid: Date } | { ok: false; grund: SprungetGrund };

/** Dommen pr. (ansøgning, art): må den sendes, og med hvilket tidspunkt? */
export function doem(r: AnsoegningTilGa, art: Art, nu: Date): Dom {
  if (!r.ga_client_id || r.ga_client_id.trim() === "") return { ok: false, grund: "ingen_ga_client_id" };
  if (art === "submitted" && !r.indsendt_at) return { ok: false, grund: "ikke_indsendt" };
  const tid = somTid(art === "started" ? r.created_at : r.indsendt_at);
  if (tid === null) return { ok: false, grund: "ingen_tidspunkt" };
  if (!erIVindue(tid, nu)) return { ok: false, grund: "for_gammel" };
  return { ok: true, tid };
}

export interface GaPayload {
  client_id: string;
  timestamp_micros: number;
  events: [{ name: string; params: Record<string, string | number> }];
}

/** Parametrenes navne — ingen begynder med _, firebase_, ga_, google_ eller gtag. (Googles reserverede præfikser). */
export const PARAMETER_NAVNE = ["kilde", "utm_source", "utm_medium", "utm_campaign", "utm_content", "utm_term"] as const;

const vaerdi = (v: string | null | undefined): string | null => {
  if (typeof v !== "string") return null;
  const t = v.trim().slice(0, VAERDI_MAKS);
  return t === "" ? null : t;
};

/**
 * Payloaden — præcis de tilladte felter. session_id UDELADES, når vi ikke har et: Google
 * siger, at et NYT session_id skaber en ny session, og en opfundet session ville skille
 * ansøgerens besøg i to. Kilden og utm-mærkerne sendes som almindelige event-parametre;
 * de ses først i rapporter, når de er oprettet som brugerdefinerede dimensioner, og de
 * ÆNDRER IKKE GA4's egen trafikkilde-tilskrivning (det bærer dokumentationen ikke — se
 * README). Ingen campaign_details-hændelse: den ville tilskrive en kampagne, og det er
 * ikke vores at gøre server-side.
 */
export function bygPayload(r: AnsoegningTilGa, art: Art, tid: Date): GaPayload {
  const params: Record<string, string | number> = { engagement_time_msec: ENGAGEMENT_TIME_MSEC };
  const session = vaerdi(r.ga_session_id);
  if (session !== null) params.session_id = session;
  for (const navn of PARAMETER_NAVNE) {
    const v = vaerdi(r[navn]);
    if (v !== null) params[navn] = v;
  }
  return {
    client_id: (r.ga_client_id ?? "").trim(),
    timestamp_micros: tid.getTime() * 1000,
    events: [{ name: GA_EVENT_NAVN[art], params }],
  };
}

/**
 * Nøgler, der ALDRIG må stå i det, vi sender til Google (deres politik + vores egne felter).
 * BEMÆRK, at «name» IKKE står her: det er Googles eget påkrævede felt på en hændelse
 * (`events[].name`). Den fejl fangede prøven, første gang listen blev skrevet — derfor
 * står bemærkningen her, så ingen føjer det tilbage i den tro, at det betyder «navn».
 */
export const FORBUDTE_NOEGLER = [
  "email", "em", "ph", "navn", "telefon", "phone", "cvr", "svar", "udfordring", "hjemmeside",
  "virksomhedsnavn", "ip", "ip_hash", "client_ip_address", "user_agent", "client_user_agent",
  "fbclid", "fbc", "fbp", "user_id", "address", "user_data", "landing", "referrer",
] as const;

/** Stierne til enhver forbudt nøgle i objektet — tom = rent. */
export function findForbudteNoegler(obj: unknown, sti = ""): string[] {
  if (obj === null || typeof obj !== "object") return [];
  const ud: string[] = [];
  if (Array.isArray(obj)) { obj.forEach((v, i) => ud.push(...findForbudteNoegler(v, `${sti}[${i}]`))); return ud; }
  for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
    const her = sti ? `${sti}.${k}` : k;
    if ((FORBUDTE_NOEGLER as readonly string[]).includes(k)) ud.push(her);
    ud.push(...findForbudteNoegler(v, her));
  }
  return ud;
}

/** Låsen: kun boolean true eller strengen "true" åbner. Alt andet (null, "ja", 1) er lukket. */
export function laasErAktiv(configValue: unknown): boolean {
  return configValue === true || configValue === "true";
}

/**
 * Sender kørslen noget? Kræver dry_run: false OG (låsen ELLER debug).
 * debug rammer valideringsserveren, som IKKE lander i rapporter — derfor tilladt uden lås.
 */
export function senderRigtigt(a: { dryRun: boolean; laasAktiv: boolean; debug: boolean }): boolean {
  if (a.dryRun) return false;
  return a.laasAktiv || a.debug;
}

// ── Sporet (ga_haendelser) ───────────────────────────────────────────────────

export const SPOR_UDFALD = ["sendt", "fejl", "timeout", "ugyldig", "ingen_noegle"] as const;
export type SporUdfald = (typeof SPOR_UDFALD)[number];

export interface SporRaekke {
  event_id: string;
  udfald: SporUdfald;
  forsoeg: number;
}

/**
 * SKAL KALDET I SPORET? (rettelse 21/9 aften — fejlen i #1073.)
 *
 * FEJLEN: en debug-kørsel (`dry_run: false` + `debug: true`) rammer Googles valideringsserver,
 * som IKKE lander i rapporter — men den upsertede alligevel sporet med udfald «sendt» og
 * `sendt_at` sat. `maaForsoeges` så kun på udfaldet, så den RIGTIGE afsendelse bagefter sprang
 * hændelsen over som «allerede_sendt». README's egen bevisrækkefølge (bevis 2 debug → bevis 3
 * rigtig) ville derfor have fejlet: valideringen ville have spist beviset.
 *
 * RETTELSEN — og hvorfor den er skruet sådan sammen: i stedet for at lære `maaForsoeges` at
 * læse `debug` (og dermed have en regel, nogen kan glemme ét sted), fjernes MULIGHEDEN for
 * at forveksle: **en debug-kørsel skriver kun i sporet, når valideringen siger NEJ.** Så kan
 * der aldrig opstå en række med «sendt» og `debug = true`, og `maaForsoeges` kan blive ved
 * med at dømme på udfaldet alene.
 *
 * Tre grunde til at det er den robuste løsning frem for et ekstra `debug`-argument:
 *   1. Sandheden står i rækken selv. Enhver læser — et menneske, en SQL, en fremtidig
 *      funktion — kan stole på, at «sendt» betyder «hændelsen er i GA».
 *      `ga_haendelser_sendt_hel` (CHECK: (udfald = 'sendt') = (sendt_at is not null)) holder
 *      dermed op med at kunne lyve.
 *   2. Den fejler sikkert. Glemmer nogen reglen, findes der ingen række — og ingen række
 *      betyder «prøv igen», ikke «spring over».
 *   3. Den kræver ingen ny tilstand og ingen skemaændring på en tabel, der allerede er kørt
 *      i prod (21/9 kl. 17:48).
 *
 * Valideringens NEJ skrives derimod ALTID: «ugyldig» er den ene ting, en debug-kørsel må
 * huske, fordi payloaden så er forkert og ikke skal sendes, før den er rettet. Fejl, timeout
 * og manglende nøgle i en debug-kørsel skrives ikke: de siger intet om hændelsen, kun om
 * valideringsserveren, og de står i svaret.
 */
export function skalSkriveSpor(udfald: SporUdfald, debug: boolean): boolean {
  return debug ? udfald === "ugyldig" : true;
}

/**
 * Idempotensen — og VINDUET ER LOFTET. Der er intet forsøgsloft: så længe hændelsen er
 * inden for 72 timer, prøver vi igen (Measurement Protocol svarer aldrig med en fejlkode,
 * så et «fejl» er netværk eller 5xx — forbigående af natur). «sendt» sendes aldrig igen,
 * fordi Google ikke dedup'er; «ugyldig» (valideringen sagde nej) sendes ikke igen, før
 * payloaden er rettet.
 *
 * DEN DØMMER PÅ UDFALDET ALENE — med vilje. Den behøver ikke kende `debug`, fordi
 * `skalSkriveSpor` sørger for, at en debug-kørsel aldrig efterlader en «sendt»-række
 * (rettelse 21/9 aften). Skulle nogen en dag skrive en alligevel, ville denne dom sige
 * «allerede_sendt» om noget, der aldrig nåede Google — derfor låser gaSend.guard dom 6,
 * at upsert'en går gennem skalSkriveSpor.
 */
export function maaForsoeges(spor: SporRaekke | null): { ok: true } | { ok: false; grund: "allerede_sendt" | "ugyldig" } {
  if (!spor) return { ok: true };
  if (spor.udfald === "sendt") return { ok: false, grund: "allerede_sendt" };
  if (spor.udfald === "ugyldig") return { ok: false, grund: "ugyldig" };
  return { ok: true };
}

export interface Valideringsbesked { fieldPath?: string; description?: string; validationCode?: string }

/**
 * Svaret. I en DEBUG-kørsel betyder «sendt» kun, at valideringen ikke havde indvendinger —
 * hændelsen er IKKE i GA («Events sent to the validation server don't show up in reports»).
 * Kørslen tæller den derfor som `valideret`, og `skalSkriveSpor` holder den ude af sporet.
 *
 * Produktions-endpointet siger intet (Googles egne ord ovenfor): 2xx = «sendt»,
 * og en forkert api_secret ville se nøjagtig sådan ud. Valideringsserveren svarer med
 * validationMessages: tom liste = gyldig, ellers «ugyldig» med beskederne.
 */
export function doemGaSvar(status: number, tekst: string, debug: boolean): { udfald: SporUdfald; validering: Valideringsbesked[] | null; fejl: string | null } {
  if (status === 401 || status === 403) return { udfald: "ingen_noegle", validering: null, fejl: `HTTP ${status}` };
  if (status < 200 || status >= 300) return { udfald: status >= 500 ? "fejl" : "ugyldig", validering: null, fejl: `HTTP ${status}: ${tekst.slice(0, 200)}` };
  if (!debug) return { udfald: "sendt", validering: null, fejl: null };
  let krop: { validationMessages?: Valideringsbesked[] } | null = null;
  try { krop = JSON.parse(tekst) as { validationMessages?: Valideringsbesked[] }; } catch { krop = null; }
  if (krop === null) return { udfald: "ugyldig", validering: null, fejl: `valideringssvaret kunne ikke læses: ${tekst.slice(0, 200)}` };
  const beskeder = krop.validationMessages ?? [];
  if (beskeder.length === 0) return { udfald: "sendt", validering: [], fejl: null };
  return { udfald: "ugyldig", validering: beskeder, fejl: beskeder.map((b) => `${b.validationCode ?? "?"} ${b.fieldPath ?? ""}: ${b.description ?? ""}`.trim()).join(" · ").slice(0, 300) };
}

// ── Alarmen (princip 1) ──────────────────────────────────────────────────────

export const ALARM_NOEGLE_PRAEFIKS = "ga-send-alarm:";
export const ALARM_MAIL_LABEL = "ga-send-alarm";
export const ALARM_KLOKKE_TYPE = "drift";
/** Én mail pr. dansk kalenderdøgn. */
export function alarmNoegle(nu: Date): string {
  return `${ALARM_NOEGLE_PRAEFIKS}${kbhDato(nu)}`;
}

export interface FejletAfsendelse { event_id: string; udfald: SporUdfald; fejl: string | null; forsoeg: number }

export function alarmTekst(fejlede: readonly FejletAfsendelse[], nu: Date): { emne: string; titel: string; afsnit: string[]; blokke: { overskrift: string; tekst: string }[]; tekst: string } {
  const n = fejlede.length;
  const hvad = n === 1 ? "1 GA-hændelse" : `${n} GA-hændelser`;
  const emne = `${hvad} kunne ikke sendes — Google Analytics har brug for et menneske`;
  const titel = `Google Analytics: ${hvad} kunne ikke sendes (${kbhDato(nu)})`;
  const ugyldig = fejlede.some((f) => f.udfald === "ugyldig");
  const afsnit = [
    `ga-send-cron kunne ikke sende ${hvad} til Google Analytics (${GA_MEASUREMENT_ID}). Ansøgningerne er urørte — kun målingen mangler.`,
    ugyldig
      ? "Mindst én blev afvist af valideringen («ugyldig») — den prøves ikke igen, før payloaden er rettet. Kør en tørkørsel med debug og læs validationMessages."
      : `Fejl og timeout prøves igen ved hver kørsel, så længe hændelsen er under ${GA_VINDUE_TIMER} timer gammel — vinduet er loftet, ikke et forsøgstal.`,
  ];
  const blokke = fejlede.slice(0, 5).map((f) => ({ overskrift: f.event_id, tekst: `${f.udfald} · forsøg ${f.forsoeg}${f.fejl ? ` — ${f.fejl}` : ""}` }));
  const tekst = [emne, ...afsnit, "", ...blokke.map((b) => `${b.overskrift}: ${b.tekst}`), "", "Sporet: ga_haendelser. Tørkørsel: SELECT public.kald_edge('ga-send-cron');"].join("\n");
  return { emne, titel, afsnit, blokke, tekst };
}
